#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Django==1.8.10','console_scripts','django-admin'
__requires__ = 'Django==1.8.10'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Django==1.8.10', 'console_scripts', 'django-admin')()
    )
