#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'gunicorn==19.4.5','console_scripts','gunicorn_paster'
__requires__ = 'gunicorn==19.4.5'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('gunicorn==19.4.5', 'console_scripts', 'gunicorn_paster')()
    )
